spring.application.name=FurnitureManagement
server.port=8083

jwt.secret=ThisIsMyVerySecretKeyForFurnitureManagementSystem123456

spring.application.name=FurnitureManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/furniture_management
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true